global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'dreamshops-monitor'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # DreamShops Application
  - job_name: 'dreamshops-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL Database (via postgres-exporter)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgresql-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 5s