services:
  app:
    environment:
      JAVA_TOOL_OPTIONS: >-
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "5005:5005"

volumes:
  dreamshops-postgres-data:
    external: false   # opcional - mantém o mesmo comportamento do local