apiVersion: 1

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by: ['grafana_folder', 'alertname']
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 12h
    routes:
      - receiver: critical-alerts
        matchers:
          - severity = critical
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 1h
      - receiver: warning-alerts
        matchers:
          - severity = warning
        group_wait: 30s
        group_interval: 10m
        repeat_interval: 6h

contactPoints:
  - orgId: 1
    name: grafana-default-email
    receivers:
      - uid: email-default
        type: email
        settings:
          addresses: admin@dreamshops.local
          subject: 'DreamShops Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
          body: |
            {{ range .Alerts }}
            **Alert:** {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            **Severity:** {{ .Labels.severity }}
            **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            {{ end }}
        disableResolveMessage: false

  - orgId: 1
    name: critical-alerts
    receivers:
      - uid: email-critical
        type: email
        settings:
          addresses: admin@dreamshops.local,ops@dreamshops.local
          subject: '🚨 CRITICAL: DreamShops Alert'
          body: |
            🚨 **CRITICAL ALERT** 🚨
            
            {{ range .Alerts }}
            **Alert:** {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            **Instance:** {{ .Labels.instance }}
            **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            {{ end }}
            
            Please take immediate action!
        disableResolveMessage: false

  - orgId: 1
    name: warning-alerts
    receivers:
      - uid: email-warning
        type: email
        settings:
          addresses: admin@dreamshops.local
          subject: '⚠️ WARNING: DreamShops Alert'
          body: |
            ⚠️ **WARNING ALERT** ⚠️
            
            {{ range .Alerts }}
            **Alert:** {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            **Instance:** {{ .Labels.instance }}
            **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            {{ end }}
            
            Please investigate when possible.
        disableResolveMessage: false