apiVersion: 1

groups:
  - orgId: 1
    name: dreamshops-alerts
    folder: DreamShops
    interval: 1m
    rules:
      - uid: app-down-alert
        title: Application Down
        condition: A
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 60
              to: 0
            datasource:
              type: prometheus
              uid: prometheus-uid
            model:
              expr: up{job="dreamshops-app"}
              interval: ''
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          summary: DreamShops application is down
          description: The DreamShops application has been down for more than 1 minute
        labels:
          severity: critical

      - uid: high-error-rate-alert
        title: High Error Rate
        condition: A
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus-uid
            model:
              expr: rate(http_server_requests_seconds_count{job="dreamshops-app",status=~"4..|5.."}[5m]) / rate(http_server_requests_seconds_count{job="dreamshops-app"}[5m]) * 100 > 5
              interval: ''
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          summary: High error rate detected
          description: Error rate is above 5% for more than 2 minutes
        labels:
          severity: warning

      - uid: high-response-time-alert
        title: High Response Time
        condition: A
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus-uid
            model:
              expr: histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job="dreamshops-app"}[5m])) by (le)) > 2
              interval: ''
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          summary: High response time detected
          description: 95th percentile response time is above 2 seconds
        labels:
          severity: warning

      - uid: high-memory-usage-alert
        title: High JVM Memory Usage
        condition: A
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus-uid
            model:
              expr: jvm_memory_used_bytes{job="dreamshops-app",area="heap"} / jvm_memory_max_bytes{job="dreamshops-app",area="heap"} * 100 > 85
              interval: ''
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 3m
        annotations:
          summary: High JVM memory usage
          description: JVM heap usage is above 85% for more than 3 minutes
        labels:
          severity: warning